name: Reproduce LFS checkout issues

on:
  workflow_dispatch: {}

jobs:

  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
        attempt1: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        attempt2: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

    runs-on: ${{ matrix.runs-on }}
    name: "Attempt ${{ matrix.attempt1 }}-${{ matrix.attempt2 }}"

    steps:
      - name: Checkout actions/checkout
        uses: actions/checkout@v3
        with:
          repository: actions/checkout

      - name: Checkout LFS
        uses: ./
        with:
          repository: actions/checkout # hardcoded, otherwise doesn't work from a fork
          ref: test-data/v2/lfs
          path: lfs
          lfs: true

      - name: Verify LFS
        shell: bash
        run: __test__/verify-lfs.sh
