name: Run actions locally

on:
  workflow_dispatch: {}

jobs:

  check:
    runs-on: ubuntu-latest
    name: Trunk Check Runner
    container: catthehacker/ubuntu:runner-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: foo

      - uses: trunk-io/trunk-action@main