name: matrix if
on:
  push:
    branches: []
  
jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      o1: true
      o2: 'true'
      o3: false
      o4: 'false'

    steps:
      - shell: bash
        run: echo bash

  matrix_job:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: o1
            if-string: ${{ needs.changes.outputs.o1 }} == true
          - name: o2
            if-string: ${{ needs.changes.outputs.o2 }} == true
          - name: o3
            if-string: ${{ needs.changes.outputs.o3 }} == true
          - name: o4
            if-string: ${{ needs.changes.outputs.o4 }} == true

    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    needs: changes

    steps:
      - shell: bash
        if: needs.changes.outputs[matrix.name] == 'true'
        run: echo ${{ needs.changes.outputs[matrix.name] }}
  
  job1:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        if: false
        run: echo job1

  
  job2:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        if: true
        run: echo job2
