name: matrix if
on:
  push:
    branches: [main]
  
jobs:
  matrix_job:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: foo
            if-string: true
          
          - name: bar
            if-string: false

    name: ${{ matrix.name }}
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        if: matrix.if-string
        run: echo ${{ matrix.if-string }}
  
  job1:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        if: false
        run: echo job1

  
  job2:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        if: true
        run: echo job2
