name: Trunk

on:
  pull_request: {}

jobs:

  check:
    runs-on: ubuntu-latest
    name: Trunk Check Runner

    permissions:
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: trunk-io/trunk-action@sxlijin-patch-1
        with:
          debug: true