name: dynamic payload inputs
run-name: ${{ inputs.run-name }}
on:
  workflow_dispatch:
    inputs:
      run-name:
        description: run-name
        required: false
      job-name:
        description: job-name
        required: false
      runs-on:
        description: runs-on
        required: false
        default: "['ubuntu-latest']"
      concurrency-group:
        description: concurrency-group
        required: false

permissions:
  contents: read

jobs:
  check:
    name: ${{ inputs.job-name }}
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    concurrency:
      group: ${{ inputs.concurrency-group }}
      cancel-in-progress: true

    steps:
      - shell: bash
        run: |
          set -x
          echo ${{ inputs }}
          env | sort
