name: dynamic inputs
run-name: ${{ inputs.run-name }}
on:
  workflow_dispatch:
    inputs:
      run-name:
        description: run-name
        required: false
        default: run-name1
      job-name:
        description: job-name
        required: false
        default: job-name1
      runs-on:
        description: runs-on
        required: false
        default: "['ubuntu-latest']"
      concurrency-group:
        description: concurrency-group
        required: false
        default: group1
      matrix:
        description: matrix
        required: false
        default: '[{"job-name":"matrix-job1","runs-on":["ubuntu-latest"],"concurrency-group":"matrix-group1"},{"job-name":"matrix-job2","runs-on":["ubuntu-latest"],"concurrency-group":"matrix-group2"}]'
      matrix-fail-fast:
        description: matrix-fail-fast
        required: false
        default: "false"

permissions:
  contents: read

jobs:
  check:
    name: ${{ inputs.job-name }}
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    concurrency:
      group: ${{ inputs.concurrency-group }}
      cancel-in-progress: true

    steps:
      - shell: bash
        run: |
          set -x
          echo ${{ inputs }}
          env | sort

  matrix:
    strategy:
      fail-fast: ${{ fromJSON(inputs.matrix-fail-fast) }}
      matrix:
        include: ${{ fromJSON(inputs.matrix) }}

    name: ${{ matrix.job-name }}
    runs-on: ${{ matrix.runs-on }}
    concurrency:
      group: ${{ matrix.concurrency-group }}
      cancel-in-progress: true

    steps:
      - shell: bash
        run: |
          set -x
          echo ${{ inputs }}
          env | sort

